---

- name: Setting hostname
  hostname:
    name: "{{ server_fqdn }}"
  when: ansible_fqdn != server_fqdn

- name: Removing any entry which contains the IP and the hostname
  lineinfile:
    path: /etc/hosts
    regexp: ".* {{ server_fqdn }}.*"
    state: absent

- name: Setting timezone
  timezone:
    name: "{{ server_timezone }}"
  notify: cron restart

- name: Setting the language of the system and the keyboard
  shell: "localectl set-locale LANG=es_ES.UTF-8 && localectl set-keymap es pc105"

- name: Updating the system
  apt:
    update_cache: yes
    upgrade: yes
    force_apt_get: yes

- name: Installing the basic packages
  apt:
    name:
      - vim
      - htop
      - dnsutils
      - tree
      - mtr
      - curl
      - colordiff
      - unzip
    state: latest
    force_apt_get: yes

- name: Removing packages for software compilation
  apt:
    name: build-essential
    state: absent
    force_apt_get: yes

- name: Getting 'vim' path
  command: which vim.basic
  register: vim_path

- name: Setting 'vim' as default editor
  command: "update-alternatives --set editor {{ vim_path['stdout'] }}"
  register: vim_editor

- name: Adding vim configuration file
  copy:
    src: vim_config
    dest: /root/.vimrc
    owner: root
    group: root
    mode: 0600

- name: Adding color to the shell
  lineinfile:
    path: /root/.bashrc
    line: 'export PS1="\[\033[38;5;1m\]\u\[$(tput sgr0)\]\[\033[38;5;6m\]@\[$(tput sgr0)\]\[\033[38;5;1m\]\h\[$(tput sgr0)\]\[\033[38;5;6m\]:\[$(tput sgr0)\]\[\033[38;5;3m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\[\033[38;5;6m\]\\$\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"'

- name: Adding an extra option for the history
  lineinfile:
    path: /root/.bashrc
    regexp: "{{ item.reg }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { reg: ".*HISTTIMEFORMAT.*", line: 'HISTTIMEFORMAT="%F %T  "' }
    - { reg: ".*HISTCONTROL.*", line: "HISTCONTROL=ignoreboth" }
    - { reg: ".*HISTSIZE.*", line: "HISTSIZE=1000" }
    - { reg: ".*HISTFILESIZE.*", line: "HISTFILESIZE=2000" }
    - { reg: ".*PROMPT_COMMAND.*", line: "PROMPT_COMMAND='history -a'" }
    - { reg: ".*HISTIGNORE.*", line: "HISTIGNORE='clear:history'" }

...
