---

- name: Setting hostname
  hostname:
    name: "{{ server_fqdn }}"
  when: ansible_fqdn != server_fqdn

- name: Removing any entry which contains the IP and the hostname
  lineinfile:
    path: /etc/hosts
    regexp: ".* {{ server_fqdn }}.*"
    state: absent

- name: Setting timezone
  timezone:
    name: "{{ server_timezone }}"
  notify: cron restart

- name: Setting the language of the system and the keyboard
  shell: "localectl set-locale LANG=es_ES.UTF-8 && localectl set-keymap es pc105"

- name: Updating the system
  apt:
    update_cache: yes
    upgrade: yes
    force_apt_get: yes

- name: Installing common packages to manage the server
  apt:
    name:
      - vim
      - htop
      - dnsutils
      - tree
      - mtr
      - curl
      - colordiff
      - unzip
    state: latest
    force_apt_get: yes

- name: Removing software compilation package
  apt:
    name: build-essential
    state: absent
    force_apt_get: yes

- name: Getting 'vim' location
  command: which vim.basic
  register: vim_path

- name: Setting 'vim' as default editor
  command: "update-alternatives --set editor {{ vim_path['stdout'] }}"
  register: vim_editor

- name: Adding vim configuration file for 'root' user
  copy:
    src: vim_config
    dest: /root/.vimrc
    owner: root
    group: root
    mode: 0600

- name: Adding color to the 'root' shell
  lineinfile:
    path: /root/.bashrc
    line: 'export PS1="\[\033[0;31m\]\342\224\214\342\224\200\$([[ \$? != 0 ]] && echo \"[\[\033[0;31m\]\342\234\227\[\033[0;37m\]]\342\224\200\")[$(if [[ ${EUID} == 0 ]]; then echo "\[\033[01;31m\]root\[\033[01;33m\]@\[\033[01;96m\]\h"; else echo "\[\033[0;39m\]\u\[\033[01;33m\]@\[\033[01;96m\]\h"; fi)\[\033[0;31m\]]\342\224\200[\[\033[0;32m\]\w\[\033[0;31m\]]\n\[\033[0;31m\]\342\224\224\342\224\200\342\224\200\342\225\274 \[\033[0m\]\[\e[01;33m\]\\$\[\e[0m\] "'

- name: Adding some extra parameters to the 'root' history configuration file
  lineinfile:
    path: /root/.bashrc
    regexp: "{{ item.reg }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { reg: ".*HISTTIMEFORMAT.*", line: 'HISTTIMEFORMAT="%F %T  "' }
    - { reg: ".*HISTCONTROL.*", line: "HISTCONTROL=ignoreboth" }
    - { reg: ".*HISTSIZE.*", line: "HISTSIZE=1000" }
    - { reg: ".*HISTFILESIZE.*", line: "HISTFILESIZE=2000" }
    - { reg: ".*PROMPT_COMMAND.*", line: "PROMPT_COMMAND='history -a'" }
    - { reg: ".*HISTIGNORE.*", line: "HISTIGNORE='clear:history'" }

...
